### PR TITLE
Usb through hole

### PR DESCRIPTION
**Pull request by markfarnan**
Convert USB connector to vertical through-hole for easier hand soldering. 

Also changed 120ohm CAN terminator to SMD (was Virtual).   Should populate by default now we have solder link for it.

### CODE REVIEW

**Comment by markfarnan** [comment]
Also includes a 'Blank'  HAT Template in a subdirectory. Just connectors and blank board

**Comment by mairas** [comment]
Noticed that the LCSC part no for the conx was still the old one? Could you update that? I know it's not going to get populated, but better to have correct information in place.

**Comment by mairas** [comment]
The terminator was also earlier not connected, there was a jumper header for that. But I agree; no reason for not populating it.

**Comment by mairas** [comment]
About the blank hat: design looks good. Could you update the page data (File -> Page Settings). Also, the silk screen still had Sailor Hat _for_ ESP32. Either "with" or just SH-ESP32?

**Pull request merged**
