### PR TITLE
Add vertical USB and JTAG Connectors   tp PCB

### PR DESCRIPTION
**Pull request by markfarnan**
- Modified the USB Connector footprint to support both horizontal and vertical micro USB connectors
- Flipped the Ferrite on the USB +5 and increased track size of USB+5 going to the pin header.

- Added JTAG header to Top/Right of the board, above the ESP32
- Moved 2 SolderJumpers under the ESP32 (same as the others are)
- Re-routed top/right section

### CODE REVIEW

**Comment by KEGustafsson** [comment]
Is dedicated JTAG header needed? Pins are available from J201 and J202.
Otherwise looks good to me.

**Comment by markfarnan** [comment]
Needed,  arguably not,   but was something I wanted to ease debugging connection, as can have a single 6 pin flylead to plug in/out,  rather than hunt down the relevant pins with single wires every-time I wanted to debug something. 

Secondly, I'm probably going to have a small 'hat' on top of the board,  so that other header may not be easily accessible.

Was able to add it in the unused area and re-route to accomodate, so I don't think it is a detriment / easy to leave off ?

**Comment by KEGustafsson** [comment]
Ok. So you are actively using JTAG for debugging instead serial over USB or both?

**Comment by markfarnan** [comment]
> Ok. So you are actively using JTAG for debugging instead serial over USB or both?

Both. 
USB give programing and serial out, but not code step through debugging.  

JTAG gives step-thru  debugging direct with VSCode/Platform.IO  via OpenOCD and GDB

**Comment by mairas** [comment]
Looks good to me. JTAG was discussed on the Slack. While the pins are available on the GPIO header, having them on a dedicated connector doesn't harm either. The traces aren't long and they're not normally active, so no real EMC issues either. Merging.

**Pull request merged**
