### PR TITLE
Proto Hat & Blank to match R0.3 

### PR DESCRIPTION
**Pull request by markfarnan**
Blank
 - Holes updated to slots
 - New zone fill rules
 - Header positions for 0.3 changes

Prot-Hat
- All changes from Blank changes
- Fix SW board corner to have arc as per other boards
- Square holes for non-connected areas
- Redesigned layout after connector  moves to accomodate.

### CODE REVIEW

**Comment by mairas** [comment]
Antenna keep out silk screen can be removed. It's outside the board now. On the blank, that is.

**Comment by mairas** [comment]
Should there be ground fills on the top and bottom layers on the proto hat?

**Comment by markfarnan** [comment]
> Antenna keep out silk screen can be removed. It's outside the board now. On the blank, that is.

Was left in to remind anyone working on the board NOT to hand things over this area / just advice.   Can move it to diff layer.

**Comment by mairas** [comment]
> Was left in to remind anyone working on the board NOT to hand things over this area / just advice. Can move it to diff layer.

If you _can_ do a layer move, maybe. But it doesn't harm much either.

**Comment by mairas** [comment]
I'd drop the last proto pad column to make room for a ground fill around the proto area. At the moment the ground trace is a 16 cm long antenna. That'd at least halve the length.

**Comment by mairas** [comment]
Done with the comments.

**Comment by mairas** [comment]
OK, actually it's at least grounded at several locations to the main board, so it's not that bad. But ground planes wouldn't harm, nevertheless.

**Pull request merged**
