### PR TITLE
Modify ESP32 footprint for Hand Soldering

### PR DESCRIPTION
**Pull request by markfarnan**
Modify ESP32 footprint for Hand Soldering
- Extended all pads 1mm outwards
- Re-route affected tracks / vias. 
- Rearranged 0-Ohm links and EN/CLK area for new footprint
- Added 3V3 and GND pads to corners of Prototype Area
- Tidied up Silkscreen

### CODE REVIEW

**Comment by mairas** [comment]
One of the decoupling caps at the extreme NE of the board could be removed to get a bit more breathing room. But now that they fit, no need.

**Comment by mairas** [comment]
Could you move the RXD and TXD 0Rs a bit further apart? They're a bit close now for easy hand-soldering removal or retracing.

**Comment by mairas** [comment]
Other than that, good to merge.

**Comment by markfarnan** [comment]
Fix spacing, Reviewed changes with Mairas and agreed it is now fine.

**Pull request merged**
